[package]
name = "teaclave_database_service_enclave"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave Database Service enclave"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "teaclave_database_service_enclave"
crate-type = ["staticlib", "rlib"]

[features]
default = []
mesalock_sgx = [
  "sgx_tstd",
  "teaclave_attestation/mesalock_sgx",
  "teaclave_proto/mesalock_sgx",
  "teaclave_ipc/mesalock_sgx",
  "teaclave_rpc/mesalock_sgx",
  "teaclave_service_config/mesalock_sgx",
  "teaclave_service_enclave_utils/mesalock_sgx",
  "teaclave_types/mesalock_sgx",
  "rusty-leveldb/mesalock_sgx",
]
cov = ["teaclave_service_enclave_utils/cov"]
enclave_unit_test = ["teaclave_ipc/enclave_unit_test", "sgx_tunittest"]

[dependencies]
anyhow    = { version = "1.0.26" }
cfg-if    = { version = "0.1.9" }
log       = { version = "0.4.6" }
serde     = { version = "1.0.92" }
thiserror = { version = "1.0.9" }

rusty-leveldb                  = { path = "../../../common/rusty_leveldb_sgx" }
teaclave_attestation           = { path = "../../../attestation" }
teaclave_config                = { path = "../../../config" }
teaclave_proto                 = { path = "../../proto" }
teaclave_ipc                   = { path = "../../../ipc" }
teaclave_rpc                   = { path = "../../../rpc" }
teaclave_service_config        = { path = "../../../utils/service_config" }
teaclave_service_enclave_utils = { path = "../../../utils/service_enclave_utils" }
teaclave_types                 = { path = "../../../types" }


sgx_tstd      = { version = "1.1.0", features = ["net", "thread", "backtrace"], optional = true }
sgx_tunittest = { version = "1.1.0", optional = true }
sgx_types     = { version = "1.1.0" }
