[package]
name = "kmeans"
version = "0.1.0"
authors = ["m3ngyang <yangm3ng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesatee_sdk = { path = "../../mesatee_sdk" }
lazy_static = { version = "1.3.0" }
serde_derive = { version = "1.0.92" }
serde_json = { version = "1.0.39" }
serde = { version = "1.0.92" }
