[workspace]

members = [
  "services/access_control/app",
  "services/authentication/app",
  "services/storage/app",
  "services/execution/app",
  "services/frontend/app",
  "services/management/app",
  "tests/unit_tests/app",
  "tests/functional_tests/app",
  "tests/integration_tests/app",
]

exclude = [
]

[patch.crates-io]
# We cannot remove these crates, because proto crates depend on them
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.0" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.0" }
