[package]
name = "acs_proto"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "RPC protocol of ACS."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd", "mesatee_core/mesalock_sgx"]
cov = ["sgx_cov"]

[dependencies]
mesatee_core = { version = "0.1.0" }
serde        = { version = "1.0.39" }
serde_json   = { version = "1.0.39" }
serde_derive = { version = "1.0.92" }
uuid         = { version = "0.7.4", features = ["v4"] }

sgx_cov      = { version = "1.1.0", optional = true }
sgx_tstd     = { version = "1.1.0", features = ["net", "backtrace"], optional = true }
sgx_types    = { version = "1.1.0" }
