[package]
name = "tms_common_proto"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "RPC protocol of TMS."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd"]
cov = ["sgx_cov"]

[dependencies]
cfg-if       = { version = "0.1.9" }
serde        = { version = "1.0.39" }
serde_json   = { version = "1.0.39" }
serde_derive = { version = "1.0.92" }

sgx_cov  = { version = "1.1.0", optional = true }
sgx_tstd = { version = "1.1.0", features = ["net", "backtrace"], optional = true }
