[package]
name = "teaclave_types"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave types"
license = "Apache-2.0"
edition = "2018"

[features]
default = [
    "protected_fs_rs/default",
]
mesalock_sgx = [
    "sgx_tstd",
    "protected_fs_rs/mesalock_sgx",
]
enclave_unit_test = []

[dependencies]
protected_fs_rs  = { path = "../common/protected_fs_rs", default-features = false}

anyhow       = { version = "1.0.26" }
sgx_types    = { version = "1.1.0" }
hex          = { version = "0.4.0" }
serde        = { version = "1.0.92", features = ["derive"] }
toml         = { version = "0.5.3" }
ring         = { version = "0.16.5" }
thiserror    = { version = "1.0.9" }

sgx_tstd = { version = "1.1.0", features = ["net", "backtrace"], optional = true }