[package]
name = "builtin_ordered_set_intersect"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "builtin_ordered_set_intersect function example using Teaclave client SDK."
license = "Apache-2.0"
edition = "2018"

[dependencies]
teaclave_client_sdk = { path = "../../../sdk/rust/" }
anyhow = { version = "1.0.26" }
pem = "0.7.0"
