[package]
name = "teaclave_execution_service"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave worker."
license = "Apache-2.0"
build = "build.rs"
edition = "2018"

[features]
default = []

[dependencies]
log         = { version = "0.4.6" }
env_logger  = { version = "0.7.1" }
anyhow      = { version = "1.0.26" }

teaclave_ipc               = { path = "../../../ipc" }
teaclave_service_app_utils = { path = "../../../utils/service_app_utils" }
teaclave_service_config    = { path = "../../../utils/service_config" }
teaclave_binder            = { path = "../../../binder" }

sgx_types = { version = "1.1.0" }
