[package]
name = "teaclave_worker"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave worker"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "teaclave_worker"
crate-type = ["staticlib", "rlib"]

[features]
default = []
mesalock_sgx = [
  "sgx_tstd",
  "teaclave_types/mesalock_sgx",
]
cov = ["sgx_cov"]
enclave_unit_test = ["sgx_tunittest"]

[dependencies]
log           = { version = "0.4.6" }
anyhow        = { version = "1.0.26" }
serde_json    = { version = "1.0.39" }
serde_derive  = { version = "1.0.93" }
serde         = { version = "1.0.92" }
thiserror     = { version = "1.0.9" }
gbdt          = { version = "0.1.0", features = ["input", "enable_training"] }
teaclave_types = { path = "../types" }

sgx_cov       = { version = "1.1.0", optional = true }
sgx_tstd      = { version = "1.1.0", features = ["net", "thread", "backtrace"], optional = true }
sgx_tunittest = { version = "1.1.0", optional = true }
sgx_types     = { version = "1.1.0" }
